#!/bin/sh
# Turn the pinned C header's struct layout into compile-time assertions in Zig.
#
# The two existing ABI checks are both *external*:
#
#   scripts/abi-check.sh        executes two probes and diffs their output
#   scripts/abi-cross-check.sh  compares layouts at compile time for targets
#                               that have no runner here
#
# Neither runs during `zig build`. A layout drift therefore produces a library
# that builds and installs cleanly and only fails later, in a script a consumer
# of this repository might never run.
#
# This closes that. A C probe emits the layout it reads out of the pinned
# header; that becomes src/abi_generated.zig, a table of offsets and sizes; and
# src/abi_contract.zig asserts src/abi.zig against it at comptime. `zig build`
# now fails on a drift, with the offending field named.
#
# The generated file is committed so it can be read without running anything,
# and `--check` fails if it is stale.
#
#   sh scripts/abi-generate.sh          # regenerate
#   sh scripts/abi-generate.sh --check  # fail if the committed copy is stale
#
# The file is keyed by *ABI class* (pointer and size_t width), not by compiler
# triple, so every LP64 host regenerates byte-identical content -- arm64 macOS
# and x86-64 Linux in CI included. src/abi_contract.zig asserts only when the
# build target is in the recorded class; other targets stay covered by
# abi-cross-check.sh, and `zig build diagnose` says which case applies.
#
# Deliberately excluded from the file: the compiler triple, and `char`
# signedness. Neither is a layout property, and both differ between hosts that
# share a layout. Signedness is reported by `zig build diagnose` instead.
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
UP="$ROOT/upstream/pdjson"
GEN="$ROOT/src/abi_generated.zig"

CHECK_ONLY=0
[ "${1:-}" = "--check" ] && CHECK_ONLY=1

TMP=${TMPDIR:-/tmp}/pdjson-abi-gen.$$
mkdir -p "$TMP"
trap 'rm -rf "$TMP"' EXIT

# The probe includes only the pinned public header. It never sees pdjson.c.
cat > "$TMP/emit.c" <<'PROBE'
#include <stdio.h>
#include <stddef.h>
#include "pdjson.h"

#define F(st, path) \
    printf("    .{ .@\"struct\" = \"%s\", .path = \"%s\", .offset = %zu, .size = %zu },\n", \
           #st, #path, offsetof(struct st, path), sizeof(((struct st *)0)->path))

#define E(n) printf("    .{ .name = \"%s\", .value = %d },\n", #n, (int)n)

int main(void)
{
    puts("//! GENERATED by scripts/abi-generate.sh -- do not edit by hand.");
    puts("//!");
    puts("//! The layout that the pinned upstream/pdjson/pdjson.h dictates,");
    puts("//! emitted by a C probe that includes that header and nothing else.");
    puts("//! src/abi_contract.zig asserts src/abi.zig against this table at");
    puts("//! comptime, so a drift fails `zig build` rather than a later script.");
    puts("//!");
    puts("//! Regenerate:  sh scripts/abi-generate.sh");
    puts("//! Staleness:   sh scripts/abi-generate.sh --check");
    puts("");
    puts("/// Keyed by ABI class rather than by compiler triple, so every host in");
    puts("/// the same class regenerates byte-identical content. The contract is");
    puts("/// asserted only when the build target matches these two widths.");
    printf("pub const pointer_size = %zu;\n", sizeof(void *));
    printf("pub const size_t_size = %zu;\n", sizeof(size_t));
    puts("");
    printf("pub const sizeof_json_stream = %zu;\n", sizeof(struct json_stream));
    printf("pub const alignof_json_stream = %zu;\n", (size_t)_Alignof(struct json_stream));
    printf("pub const sizeof_json_source = %zu;\n", sizeof(struct json_source));
    printf("pub const alignof_json_source = %zu;\n", (size_t)_Alignof(struct json_source));
    printf("pub const sizeof_json_allocator = %zu;\n", sizeof(struct json_allocator));
    printf("pub const alignof_json_allocator = %zu;\n", (size_t)_Alignof(struct json_allocator));
    printf("pub const sizeof_enum_json_type = %zu;\n", sizeof(enum json_type));
    printf("pub const enum_json_type_is_signed = %s;\n",
           ((enum json_type)-1 < (enum json_type)1) ? "true" : "false");

    puts("");
    puts("pub const Field = struct {");
    puts("    @\"struct\": []const u8,");
    puts("    /// Dotted path from the named struct, so nested members and union");
    puts("    /// arms are asserted too, not just the top level.");
    puts("    path: []const u8,");
    puts("    offset: usize,");
    puts("    size: usize,");
    puts("};");
    puts("");
    puts("pub const fields = [_]Field{");
    F(json_stream, lineno);
    F(json_stream, stack);
    F(json_stream, stack_top);
    F(json_stream, stack_size);
    F(json_stream, next);
    F(json_stream, flags);
    F(json_stream, data);
    F(json_stream, data.string);
    F(json_stream, data.string_fill);
    F(json_stream, data.string_size);
    F(json_stream, ntokens);
    F(json_stream, source);
    F(json_stream, alloc);
    F(json_stream, errmsg);
    F(json_source, get);
    F(json_source, peek);
    F(json_source, position);
    F(json_source, source);
    F(json_source, source.stream.stream);
    F(json_source, source.buffer.buffer);
    F(json_source, source.buffer.length);
    F(json_source, source.user.ptr);
    F(json_source, source.user.get);
    F(json_source, source.user.peek);
    F(json_allocator, malloc);
    F(json_allocator, realloc);
    F(json_allocator, free);
    puts("};");

    puts("");
    puts("pub const Enumerator = struct { name: []const u8, value: c_int };");
    puts("");
    puts("pub const enumerators = [_]Enumerator{");
    E(JSON_ERROR);
    E(JSON_DONE);
    E(JSON_OBJECT);
    E(JSON_OBJECT_END);
    E(JSON_ARRAY);
    E(JSON_ARRAY_END);
    E(JSON_STRING);
    E(JSON_NUMBER);
    E(JSON_TRUE);
    E(JSON_FALSE);
    E(JSON_NULL);
    puts("};");
    return 0;
}
PROBE

cc -std=c11 -pedantic -Wall -Wextra -I "$UP" -o "$TMP/emit" "$TMP/emit.c"
"$TMP/emit" > "$TMP/abi_generated.zig"

CLASS=$(sed -n 's/^pub const pointer_size = \([0-9]*\);/\1/p' "$TMP/abi_generated.zig")

if [ "$CHECK_ONLY" -eq 1 ]; then
    [ -f "$GEN" ] || {
        echo "FAIL: $GEN is missing; run 'sh scripts/abi-generate.sh'" >&2
        exit 1
    }
    HAVE=$(sed -n 's/^pub const pointer_size = \([0-9]*\);/\1/p' "$GEN")
    if [ "$HAVE" != "$CLASS" ]; then
        echo "SKIP: committed contract is for ${HAVE}-byte pointers, this host has ${CLASS}" >&2
        echo "      staleness cannot be judged across ABI classes; abi-cross-check.sh covers this target" >&2
        exit 0
    fi
    if cmp -s "$TMP/abi_generated.zig" "$GEN"; then
        echo "  src/abi_generated.zig matches the pinned header on this host"
    else
        echo "FAIL: src/abi_generated.zig is stale" >&2
        diff -u "$GEN" "$TMP/abi_generated.zig" | head -30 >&2
        echo "      run 'sh scripts/abi-generate.sh' to regenerate" >&2
        exit 1
    fi
else
    cp "$TMP/abi_generated.zig" "$GEN"
    FIELDS=$(grep -c '^    .{ .@"struct"' "$TMP/abi_generated.zig")
    ENUMS=$(grep -c '^    .{ .name' "$TMP/abi_generated.zig")
    echo "  wrote src/abi_generated.zig: $FIELDS field(s), $ENUMS enumerator(s), ${CLASS}-byte pointers"
fi
