#!/usr/bin/env python3
"""Render captured terminal output to PNG for the Devfolio gallery.

These are not illustrations. Every image is a faithful, monospaced rendering of
bytes that a real command actually wrote to a real terminal, captured to
/tmp/shots/*.txt by the capture step and rendered here verbatim. Nothing is
retyped, edited for effect, or generated by a model.

Usage:  render-screenshots.py <input-dir> <output-dir>
"""
from __future__ import annotations

import pathlib
import sys

from PIL import Image, ImageDraw, ImageFont

BG = (13, 17, 23)
FG = (201, 209, 217)
PROMPT = (126, 231, 135)
GOOD = (86, 211, 100)
BAD = (255, 123, 114)
DIM = (125, 133, 144)
ACCENT = (121, 192, 255)

PAD = 28
LINE = 22
FONT_SIZE = 15

FONT_CANDIDATES = [
    "/System/Library/Fonts/Menlo.ttc",
    "/System/Library/Fonts/SFNSMono.ttf",
    "/System/Library/Fonts/Monaco.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
]


def load_font(size: int):
    for path in FONT_CANDIDATES:
        if pathlib.Path(path).exists():
            try:
                return ImageFont.truetype(path, size)
            except OSError:
                continue
    return ImageFont.load_default()


def colour_for(line: str):
    s = line.strip()
    if s.startswith("$"):
        return PROMPT
    if "FAIL" in s or "ERROR" in s or "error:" in s or "SEGV" in s or "runtime error" in s:
        return BAD
    if (s.startswith("PASS") or "OK" in s.split() or "pass," in s
            or "IDENTICAL" in s or "VERIFY OK" in s or "CAUGHT" in s
            or s.endswith("passed") or "0 divergences" in s or "divergences=0" in s):
        return GOOD
    if s.startswith("#") or s.startswith("==") or s.startswith("|"):
        return DIM
    if s.startswith("[") and "]" in s[:6]:
        return ACCENT
    return FG


def render(text: str, out_path: pathlib.Path, title: str) -> None:
    lines = text.rstrip("\n").split("\n")
    font = load_font(FONT_SIZE)
    title_font = load_font(FONT_SIZE + 1)

    probe = Image.new("RGB", (10, 10))
    d = ImageDraw.Draw(probe)
    char_w = d.textlength("M", font=font)

    width_chars = max((len(l) for l in lines), default=40)
    width_chars = max(width_chars, len(title) + 4)
    w = int(PAD * 2 + char_w * min(width_chars, 118)) + 8
    h = PAD * 2 + LINE * (len(lines) + 3)

    img = Image.new("RGB", (w, h), BG)
    d = ImageDraw.Draw(img)

    # Window chrome, so it reads as a terminal capture rather than a diagram.
    d.rectangle([0, 0, w, 34], fill=(22, 27, 34))
    for i, c in enumerate([(255, 95, 86), (255, 189, 46), (39, 201, 63)]):
        d.ellipse([16 + i * 20, 12, 26 + i * 20, 22], fill=c)
    d.text((86, 10), title, font=title_font, fill=DIM)

    y = 34 + PAD // 2
    for line in lines:
        d.text((PAD, y), line[:118], font=font, fill=colour_for(line))
        y += LINE

    img.save(out_path)
    print(f"  {out_path.name}  {w}x{h}  ({len(lines)} lines)")


TITLES = {
    "00": "make verify",
    "01": "upstream test suite against the Zig library",
    "02": "differential: fixed corpus + JSONTestSuite",
    "03": "provenance: pinned upstream hashes",
    "04": "upstream bug #36 under ASan + UBSan",
    "05": "byte-identical behaviour transcripts",
    "06": "benchmark: C vs Zig",
    "07": "fuzz session and harness mutation testing",
}


def main() -> int:
    src = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "/tmp/shots")
    dst = pathlib.Path(sys.argv[2] if len(sys.argv) > 2 else "/tmp/shots/png")
    dst.mkdir(parents=True, exist_ok=True)

    for f in sorted(src.glob("*.txt")):
        key = f.name[:2]
        render(f.read_text(errors="replace"), dst / f"{f.stem}.png",
               TITLES.get(key, f.stem))
    return 0


if __name__ == "__main__":
    sys.exit(main())
