#!/usr/bin/env python3
"""Validate CLAIMS.json against the artifacts, and against the public copy.

Two directions, both of which have to hold:

  1. Every claim in the ledger must be backed by a value in a generated
     artifact. A claim whose artifact is missing, or whose check does not hold,
     fails -- it does not quietly downgrade to "unverified".

  2. Every headline number in README.md must come from the ledger. The README
     block between <!-- CLAIMS:BEGIN --> and <!-- CLAIMS:END --> is generated by
     scripts/report.py, and this script regenerates it and requires a match, so
     a stale metric in the README is a hard failure rather than something a
     reader has to notice.

Run by `make verify` as the last step, so it validates artifacts that were just
produced rather than whatever happened to be lying around.
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

VALID_STATUS = {
    "verified",                          # an executable artifact shows it
    "failed",                            # checked and did not hold
    "unavailable",                       # could not be checked in this run
    "reported-not-independently-verified",
    "unsupported",                       # explicitly not claimed
}

VALID_SURFACES = {"readme", "devfolio", "video", "social"}


def dig(obj, path: str):
    cur = obj
    for part in path.split("."):
        if cur is None:
            return None
        if isinstance(cur, list):
            try:
                cur = cur[int(part)]
                continue
            except (ValueError, IndexError):
                return None
        if not isinstance(cur, dict) or part not in cur:
            return None
        cur = cur[part]
    return cur


def evaluate(check: dict, artifact) -> tuple[bool, str]:
    kind = check.get("kind")
    path = check.get("path")
    actual = dig(artifact, path) if path else artifact

    if kind == "equals":
        return actual == check["value"], f"{path} = {actual!r}, expected {check['value']!r}"
    if kind == "at_least":
        ok = isinstance(actual, (int, float)) and actual >= check["value"]
        return ok, f"{path} = {actual!r}, expected >= {check['value']!r}"
    if kind == "at_most":
        ok = isinstance(actual, (int, float)) and actual <= check["value"]
        return ok, f"{path} = {actual!r}, expected <= {check['value']!r}"
    if kind == "exists":
        return actual is not None, f"{path} is {actual!r}"
    if kind == "in_range":
        lo, hi = check["min"], check["max"]
        ok = isinstance(actual, (int, float)) and lo <= actual <= hi
        return ok, f"{path} = {actual!r}, expected within [{lo}, {hi}]"
    return False, f"unknown check kind {kind!r}"


def main() -> int:
    ledger_path = ROOT / "CLAIMS.json"
    if not ledger_path.exists():
        print("FAIL: CLAIMS.json is missing", file=sys.stderr)
        return 1
    ledger = json.loads(ledger_path.read_text())

    failures: list[str] = []
    checked = 0
    by_status: dict[str, int] = {}

    seen_ids = set()
    for c in ledger.get("claims", []):
        cid = c.get("id", "<no id>")
        if cid in seen_ids:
            failures.append(f"{cid}: duplicate claim id")
        seen_ids.add(cid)

        status = c.get("status")
        by_status[status] = by_status.get(status, 0) + 1
        if status not in VALID_STATUS:
            failures.append(f"{cid}: invalid status {status!r}")
            continue

        for surface in c.get("allowed_in", []):
            if surface not in VALID_SURFACES:
                failures.append(f"{cid}: unknown surface {surface!r}")

        # Anything not claimed as verified must not be advertised anywhere.
        if status != "verified" and c.get("allowed_in"):
            failures.append(
                f"{cid}: status is {status!r} but it is marked publishable in "
                f"{c['allowed_in']}")

        for field in ("text", "artifact", "command", "verified_date"):
            if not c.get(field):
                failures.append(f"{cid}: missing required field {field!r}")

        art_rel = c.get("artifact")
        if not art_rel:
            continue
        art_path = ROOT / art_rel
        if not art_path.exists():
            failures.append(f"{cid}: artifact {art_rel} does not exist")
            continue

        check = c.get("check")
        if not check:
            failures.append(f"{cid}: no check defined")
            continue

        try:
            artifact = json.loads(art_path.read_text())
        except json.JSONDecodeError as e:
            failures.append(f"{cid}: artifact {art_rel} is not valid JSON ({e})")
            continue

        ok, detail = evaluate(check, artifact)
        checked += 1
        if ok:
            print(f"  OK   {cid}  {detail}")
        else:
            failures.append(f"{cid}: check failed -- {detail}")
            print(f"  FAIL {cid}  {detail}")

    # ---- direction 2: the README block must match the ledger --------------
    readme = ROOT / "README.md"
    if readme.exists():
        sys.path.insert(0, str(ROOT / "scripts"))
        from report import render_claim_block  # noqa: E402

        text = readme.read_text()
        start, end = "<!-- CLAIMS:BEGIN -->", "<!-- CLAIMS:END -->"
        if start not in text or end not in text:
            failures.append(
                "README.md has no CLAIMS block; headline metrics must live in "
                "the generated block so they cannot drift")
        else:
            present = text.split(start)[1].split(end)[0]
            expected = "\n" + render_claim_block(ledger)
            if present != expected:
                failures.append(
                    "README.md CLAIMS block is stale -- run scripts/report.py")

        # Catch numbers that look like metrics outside the generated block.
        outside = text.split(start)[0] + text.split(end)[-1]
        ledger_numbers = set()
        for c in ledger.get("claims", []):
            ledger_numbers |= set(re.findall(r"\d[\d,\.]*", c.get("text", "")))
        stray = []
        for m in re.finditer(r"\*\*([\d][\d,\.]*)\*\*", outside):
            if m.group(1) not in ledger_numbers:
                stray.append(m.group(1))
        if stray:
            failures.append(
                f"README.md emphasises numbers not present in CLAIMS.json: {stray}")

    print()
    print(f"claims: {len(ledger.get('claims', []))} total, {checked} checked "
          f"against artifacts")
    print(f"status breakdown: {by_status}")

    if failures:
        print()
        for f in failures:
            print(f"FAIL {f}", file=sys.stderr)
        print(f"\n{len(failures)} claim validation failure(s)", file=sys.stderr)
        return 1

    print("all claims validate against their artifacts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
