//! GENERATED by scripts/abi-generate.sh -- do not edit by hand.
//!
//! The layout that the pinned upstream/pdjson/pdjson.h dictates,
//! emitted by a C probe that includes that header and nothing else.
//! src/abi_contract.zig asserts src/abi.zig against this table at
//! comptime, so a drift fails `zig build` rather than a later script.
//!
//! Regenerate:  sh scripts/abi-generate.sh
//! Staleness:   sh scripts/abi-generate.sh --check

/// Keyed by ABI class rather than by compiler triple, so every host in
/// the same class regenerates byte-identical content. The contract is
/// asserted only when the build target matches these two widths.
pub const pointer_size = 8;
pub const size_t_size = 8;

pub const sizeof_json_stream = 272;
pub const alignof_json_stream = 8;
pub const sizeof_json_source = 48;
pub const alignof_json_source = 8;
pub const sizeof_json_allocator = 24;
pub const alignof_json_allocator = 8;
pub const sizeof_enum_json_type = 4;
pub const enum_json_type_is_signed = false;

pub const Field = struct {
    @"struct": []const u8,
    /// Dotted path from the named struct, so nested members and union
    /// arms are asserted too, not just the top level.
    path: []const u8,
    offset: usize,
    size: usize,
};

pub const fields = [_]Field{
    .{ .@"struct" = "json_stream", .path = "lineno", .offset = 0, .size = 8 },
    .{ .@"struct" = "json_stream", .path = "stack", .offset = 8, .size = 8 },
    .{ .@"struct" = "json_stream", .path = "stack_top", .offset = 16, .size = 8 },
    .{ .@"struct" = "json_stream", .path = "stack_size", .offset = 24, .size = 8 },
    .{ .@"struct" = "json_stream", .path = "next", .offset = 32, .size = 4 },
    .{ .@"struct" = "json_stream", .path = "flags", .offset = 36, .size = 4 },
    .{ .@"struct" = "json_stream", .path = "data", .offset = 40, .size = 24 },
    .{ .@"struct" = "json_stream", .path = "data.string", .offset = 40, .size = 8 },
    .{ .@"struct" = "json_stream", .path = "data.string_fill", .offset = 48, .size = 8 },
    .{ .@"struct" = "json_stream", .path = "data.string_size", .offset = 56, .size = 8 },
    .{ .@"struct" = "json_stream", .path = "ntokens", .offset = 64, .size = 8 },
    .{ .@"struct" = "json_stream", .path = "source", .offset = 72, .size = 48 },
    .{ .@"struct" = "json_stream", .path = "alloc", .offset = 120, .size = 24 },
    .{ .@"struct" = "json_stream", .path = "errmsg", .offset = 144, .size = 128 },
    .{ .@"struct" = "json_source", .path = "get", .offset = 0, .size = 8 },
    .{ .@"struct" = "json_source", .path = "peek", .offset = 8, .size = 8 },
    .{ .@"struct" = "json_source", .path = "position", .offset = 16, .size = 8 },
    .{ .@"struct" = "json_source", .path = "source", .offset = 24, .size = 24 },
    .{ .@"struct" = "json_source", .path = "source.stream.stream", .offset = 24, .size = 8 },
    .{ .@"struct" = "json_source", .path = "source.buffer.buffer", .offset = 24, .size = 8 },
    .{ .@"struct" = "json_source", .path = "source.buffer.length", .offset = 32, .size = 8 },
    .{ .@"struct" = "json_source", .path = "source.user.ptr", .offset = 24, .size = 8 },
    .{ .@"struct" = "json_source", .path = "source.user.get", .offset = 32, .size = 8 },
    .{ .@"struct" = "json_source", .path = "source.user.peek", .offset = 40, .size = 8 },
    .{ .@"struct" = "json_allocator", .path = "malloc", .offset = 0, .size = 8 },
    .{ .@"struct" = "json_allocator", .path = "realloc", .offset = 8, .size = 8 },
    .{ .@"struct" = "json_allocator", .path = "free", .offset = 16, .size = 8 },
};

pub const Enumerator = struct { name: []const u8, value: c_int };

pub const enumerators = [_]Enumerator{
    .{ .name = "JSON_ERROR", .value = 1 },
    .{ .name = "JSON_DONE", .value = 2 },
    .{ .name = "JSON_OBJECT", .value = 3 },
    .{ .name = "JSON_OBJECT_END", .value = 4 },
    .{ .name = "JSON_ARRAY", .value = 5 },
    .{ .name = "JSON_ARRAY_END", .value = 6 },
    .{ .name = "JSON_STRING", .value = 7 },
    .{ .name = "JSON_NUMBER", .value = 8 },
    .{ .name = "JSON_TRUE", .value = 9 },
    .{ .name = "JSON_FALSE", .value = 10 },
    .{ .name = "JSON_NULL", .value = 11 },
};
